version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smartsheet_user
      POSTGRES_PASSWORD: smartsheet_pass
      POSTGRES_DB: smartsheet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
