services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chatsheetai
      POSTGRES_INITDB_ARGS: "--wal-segsize=1"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chatsheetai"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # Add an initialization directory for SQL scripts if needed.
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optionally, other services such as the backend server
  server:
    build: .
    command: npm run dev:server
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/chatsheetai
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SMARTSHEET_ACCESS_TOKEN: ${SMARTSHEET_ACCESS_TOKEN}
      SMARTSHEET_WEBHOOK_SECRET: ${SMARTSHEET_WEBHOOK_SECRET}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: npm run dev:client -- --host
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_WS_URL: ws://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  db-data:
  redis-data:
