model_list:
  - model_name: gpt-4
    litellm_params:
      model: gpt-4o-2024-08-06
      api_base: https://ai-idha-sbx-scus-001.openai.azure.com/
      api_version: "2024-08-01-preview"
      api_key: ${AZURE_OPENAI_API_KEY}

litellm_settings:
  drop_params: True
  set_verbose: True

environment_variables:
  AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
